[2nd week] 3단계 요구사항1 검증 완료
djawnstj/DIY-JavaMVC pull request #14
Opened 2024-05-21 06:25 UTC by annnhs

PR 올리는데 오래걸렸네요...

그래도 이제 좀 슬슬 재밌어지는 것 같아요~~

2024-05-21 07:32 UTC, djawnstj reviewed
호성님! 잘해주셨습니다.
이제는 완전한 프레임워크의 느낌이 나는 프로젝트 같아요!
천천히 필요한 기능을 구현 해줄 일만 남은 것 같습니다ㅎㅎ👍🏻

몇 가지 수정이 필요한 내용들 리뷰 남겼으니 확인 부탁드려요.

2024-05-21 07:32 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +        }
이 코드는 빈을 생성하는 역할을 하는거 같은데 `init()` 메서드에 있는게 조금 어색한거 같아요.
또 `getAutoWired()`, `putInBeanMap()` 메서드 명도 조금 모호한 느낌이 있네요😓

`BeanFactory` 클래스 관점에서 해당 메서드들이 하는 역할을 메서드 명으로 지어주는게 좋을거 같습니다.

2024-05-21 07:32 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
>      }
메서드 반환값으로 `Stream` 자체를 반환하는 것은 좋지 않은거 같아요.
`Stream` 이 갖는 특징 때문인데요, '[[Effective Java] 반환 타입으로는 Stream 보다 Collection이 낫다. (item 47)](https://colevelup.tistory.com/15)' 한번 호시는걸 추천드립니다!

그리고 `getConstructorsMoreThanOne` 이름의 메서드인데 찾은 생성자가 하나인 경우엔 빈을 생성하는 `putInBeanMap()` 메서드가 호출되고 있어요.
이 메서드의 역할이 맞는지가 첫번째 의문이고 `init()` 메서드에서 `getAutoWiredConstructors()` 메서드를 호출한 후에 `putInBeanMap()` 메서드를 호출하는 순서로 구현해주셨는데
다른 위치에서 빈을 생성하고 있는 상황도 조금 어생한듯 합니다!

2024-05-21 07:32 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +        }
`for` 문과 `if` 문이많아서 메서드의 복잡도를 높이고 있어요.
`Stream` 을 활용해서 해결 해보거나 메서드를 분리하는게 좋을 것 같습니다.

2024-05-21 07:32 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +        }
1.
`Constructor` 의 접근 제어자를 변경하는 것은 생각보다 위험한 작업이에요.
`public` 으로 바꿨으면 `private` 으로 바꿔줄 필요가 있습니다.

`try-catch-finally` 를 활용해서 이 작업이 끝난 후 반드시 접근 제어자가 `private` 로 변경되도록 수정하면 더 좋은 코드가 될거 같아요.

2.
생성자의 파라미터가 없는 경우에 별도로 `beanMap.put` 을 해주고 있는데요, `Constructor` 클래스의 `newInstance()` 메서드를 확인해보면 파라미터로 가변 인자를 받는 것을 볼 수 있어요.
굳이 파라미터가 없을 경우 생성 코드를 분리하지 않고 `List<Object> params` 가 빈 리스트가 되도록 만들어 줄 수 있지 않을까요?

2024-05-21 07:32 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +        return params;
`getParametersThroughBeanMap()` 메서드를 호출하는 코드는 `putInBeanMap()` 메서드 밖에 존재하지 않아요.
하지만 `putInBeanMap` 메서드에서는 반환 값을 `toArray()` 를 통해 타입을 변환해주고 있어요.

메서드를 호출한 관점에서 사용하기 편하도록 반환해주는 것이 좋습니다!

그리고 `params.add(beanMap.getOrDefault(param.getName(), param))` 를 통해 파라미터에 필요한 빈들을 모아주고 있는데요, 만약 파라미터로 필요한 빈이 생성되기 전이어도 의도한 대로 의존성 주입이 잘 이루어 질 까요??

해당 내용도 테스트를 통해 검증을 하면 좋을 것 같아요.
참고로 스캔된 빈은 같은 패키지에선 이름 순서로 정렬되는거 같더라고요!

`UserService(PayRepository)` 이런식의 구조라면 `UserService` 가 생성되는 시점에 `PayRepository` 가 생성되어 있지 않는 케이스를 테스트 해볼 수 있을 것 같아요.

2024-05-21 07:32 UTC, djawnstj commented on src/test/java/com/djawnstj/mvcframework/bean/BeanFactoryTest.java
> +        beanFactory.init();
`조회한 클래스 정보들을 이용해 빈 생성` 테스트인데 when 절에는 `getBean` 을 호출하고 있어요.
'빈 생성' 을 담당하는 메서드가 when 절에 위치해야 하지 않을까요?

2024-05-23 00:27 UTC, djawnstj requested changes
호성님!
전체적으로 코드가 너무 깔끔해서 메서드를 읽기 편했습니다.💯👍🏻
기능적으로는 문제가 없는 것 같아요.

이제 다음 요구사항 진행해주시면 좋을 것 같습니다!!
단계 별로 하나의 PR 을 유지하려고 해서 해당 브랜치에 다음 요구사항 작업해주시면 될거 같아요!

2024-05-23 00:27 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +        }
`constructor.newInstance(parameters);` 를 해주는데 생성자의 접근 제어자 변경하는 코드가 없어요😭
이러면 새로운 인스턴스를 생성할 때 문제가 생길 수도 있을 것 같습니다.

2024-05-23 00:27 UTC, djawnstj commented on src/test/java/com/djawnstj/mvcframework/bean/BeanFactoryTest.java
> +    @RepeatedTest(value = 10)
`@RepeatedTest` 애너테이션도 테스트 메서드를 명시하는 애너테이션의 역할을 하기 때문에 `@Test` 애너테이션과 같이 쓰지 않는 것이 좋습니다!

별개로 `@RepeatedTest` 를 사용한 이유도 궁금하네요!

2024-05-23 00:59 UTC, annnhs commented on src/test/java/com/djawnstj/mvcframework/bean/BeanFactoryTest.java
> +    @RepeatedTest(value = 10)
어제 실행할 때마다 결과가 달랐어서 그냥 여러 번 실행하게 해봤습니다 :)

2024-05-25 16:34 UTC, djawnstj requested changes
호성님
주말에도 코드 작업 해주셨군요!!👍🏻💯

지금까지 만들었던 빈 생성 기능에 추가로 다른 형태의 빈 생성 코드가 만들어 져야 하는데요,
이런 여러 형태의 빈 생성이 존재하다 보니 복잡한 케이스가 많이 존재할거에요.
이럴수록 역할을 단순하게 생각하는 것을 추천합니다!

결국 `@Component` 도, `@Bean` 도 동적으로 생성해야 할 빈이에요.
다만 '생성하는 시점'에서 생성자로 생성하냐 메서드로 생성하냐 차이만 존재할 듯 하네요.

구조를 생각해보고 고민이 있다면 언제든 말씀 주세요!

2024-05-25 16:34 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +        Set<Class<?>> configurationSet = componentScanner.scan(packageName, Configuration.class);
어차피 `Configuration` 들도 스캔 대상인데 두번 스캔한 이유가 있을까요??

2024-05-25 16:34 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +    }
빈을 생성하기 위해 필요한 파라미터를 생성하는 역할인데 `Method`, `Consturctor` 구분해하는 메서드가 필요할까요?
결국 둘 다 빈을 생성하기 위한 파라미터를 생성하는 것인데요.

2024-05-25 16:34 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +    }
이 메서드는 여러 문제가 있어요.
1. `@Configuration` 클래스는 빈 생성이 안되고 있다.
2. `@Component` 가 붙은 클래스를 빈 생성할 때, 참조(의존)하고 있는 객체가 `@Bean` 으로 생성된 객체라면 의존성 주입이 안된다.
3. `@Bean` 메서드에서 `@Bean` 으로 빈 등록된 파라미터를 받는다면 정상적으로 주입되지 않는다.

결국 `@Bean` 이든 `Component` 든 프레임워크 입장에선 동적으로 생성, 관리 해줘야 하는 빈이긴 마찬가지에요.
이 두갤 구분하려 하지 않는게 좋을 것 같습니다.

또 의존 관계에 대해서 고민해볼 필요가 있어요.
``` java
@Component
class UserService {
    private final UserRepository;
}

@Bean
public UserRepository userRepository();
```
같은 의존 관계는 지금 코드에서 정상적으로 주입될거 같지 않아요.

2024-05-30 01:49 UTC, djawnstj requested changes
호성님
보완할 부분이 조금 더 있는 것 같습니다!
[지난번 피드백](https://github.com/djawnstj/DIY-JavaMVC/pull/14#discussion_r1614766764)을 참고해서 빠지는 부분이 없도록 만들면 될 것 같아요.

일단 중요한건 '`@Bean` 이든 `@Component` 든 모두 빈 인건 마찬가지다!' 입니다.
이 두 개를 분리해서 생각하면 정상적으로 기능이 작동 되지 않을 것 같아요😓

2024-05-30 01:49 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +        }
빈을 만드는 중간에 `@Configuration` 을 만나면 `@Bean` 메서드를 실행시켜 주는 것 같아요.
이런 경우 어떤 `@Configuration` 클래스에서 필요한 의존성 주입이 `@Bean` 메서드로 만들어 주고 있고,
아직 해당 빈이 생성되기 전이라면 여전히 문제가 있을 것 같아요.

2024-05-30 01:49 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +
빈을 생성할 때 여전히 해당 타입이 빈으로 생성해도 되는 타입인지 검증이 안되고 있어요😭

2024-05-31 01:14 UTC, djawnstj requested changes
호성님!
이제 문제가 몇 개 남지 않은 것 같습니다!
곧 다음 주차 미션으로 넘어가셔도 될 것 같아요.👍🏻👍🏻👍🏻👍🏻👍🏻
수정해야 하는 몇가지 부분 남겨 뒀으니 확인 부탁드립니다!

2024-05-31 01:14 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +    private void createBeanMap(final Class<?> clazz) {
아직 파라미터로 받은 `Class<?> clazz` 가 빈으로 생성해도 되는지 체크를 안해주고 있어요😭😭
`beanClasses` 에 담겨 있는 Class 타입만 빈으로 생성해야 하지 않을까요?

2024-05-31 01:14 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +
메서드로 빈 생성 좋습니다!
다만 지금 로직으로는 메서드로 생성 한번 한 후 아래의 `try-catch` 블럭에서 생성자로 한번 더 생성이 될 것 같아요.

2024-05-31 06:06 UTC, djawnstj approved these changes
호성님 수고하셨어요~
어렵고 긴 미션인데 끝까지 잘 해주셨어요.
다음 미션들도 화이팅 입니다!😁

2024-05-31 06:06 UTC, merged