[2nd week] 1단계 리플렉션 실습, 2단계 동적 빈 생성
djawnstj/DIY-JavaMVC pull request #9
Opened 2024-05-02 05:55 UTC by annnhs

1단계 리플렉션 실습 부분
ReflectionTest.java 에서 @PrintView 어노테이션 메서드를 호출까지는 했는데, 검증하는 방법이 까다롭네요.

2024-05-02 06:17 UTC, djawnstj requested changes
호성님 1단계, 2단계 미션 잘 해주셨습니다!
몇 가지 피드백 남겼으니 확인하고 다시 요청해주세요!

2024-05-02 06:17 UTC, djawnstj commented on src/test/java/study/reflection/bean/ComponentScannerTest.java
> +        }).collect(Collectors.toList());
애너테이션으로 클래스 정보 가져오는 작업 잘 해주셨어요💯
다만 몇가지 아쉬운 부분이 있는데, `Service`, `Repository` 외에도 요구사항에 있던 `Component`, `Configuration`, `Controller` 애너테이션도 조회하는 검증이 있었으면 해요.

정확하겐 해당 애너테이션을 가진 클래스만 반환하는 메서드가 스캐너에 있어야 하지 않나 생각도 듭니다! 
(그렇게 되면 그 클래스가 프로덕션 코드가 되고 테스트 코드는 지금처럼 길어질 필요 없이 필요한 메서드를 호출하게 돼서 더 좋은 테스트 코드가 될거 같아요)

그리고 만약 `RestController`, `Properties` 등 컴포넌트 스캔이 되어야 하는 애너테이션이 추가된다면 그때마다 애너테이션을 하드코딩으로 넣어줘야 할까요??
일반 클래스를 상속하듯이 애너테이션에도 상속과 비슷한 개념이 있는데 찾아보면 힌트가 될듯 합니다!

2024-05-02 06:17 UTC, djawnstj commented on src/test/java/study/reflection/bean/ComponentScannerTest.java
> +        userRepository.save(id, user);
이 테스트에선 위 부분이 의미가 있는 행위인지를 잘 모르겠어요😂

2024-05-02 06:17 UTC, djawnstj commented on src/test/java/study/reflection/bean/Repository.java
우리가 만드는건 MVC 프레임워크인데, 사용자 입장에선 `@Repository` 라는 애너테이션을 붙여서 싱글톤 객체 생성을 프레임워크에게 위임해주고 싶을거 같아요.
그런 기능을 만들려면 사용자도 애너테이션을 사용해야 하므로 패키지가 `test` 보단 `main` 에 있는게 좋을거 같아요.

2024-05-02 06:17 UTC, djawnstj commented on src/test/java/study/reflection/bean/Service.java
위 피드백과 동일합니다!

2024-05-02 07:05 UTC, annnhs commented on src/test/java/study/reflection/bean/ComponentScannerTest.java
> +        }).collect(Collectors.toList());
스캐너는 건들지 말아야지 하는 생각 때문에 그 생각은 못했네요. :(

하드코딩으로 넣어준 부분은 저도 하면서 마음에 들지 않았는데 한번 찾아보겠습니다~

2024-05-02 07:07 UTC, annnhs commented on src/test/java/study/reflection/bean/ComponentScannerTest.java
> +        userRepository.save(id, user);
UserService 에서 UserRepository 안에 save 했던 User가 있는지 검증해보려다가 남은 잔재들이네요...

2024-05-07 01:36 UTC, djawnstj requested changes
호성님, 아직 프레임워크 그리고 싱글톤 개념이 익숙하지 않은거 같아요.

지금 저희가 만드는건 프레임 워크이지 하나의 애플리케이션이 아니에요.
완성품을 만든다고 생각하지 말고 `내가 만든 제품을 누군가가 이용해서 완성시킨다` 라는 생각으로 개발을 하면 좋을거 같아요.

싱글톤은 프로그램이 실행중인 상황에서 한개의 인스턴스가 존재하는 방식이에요.
누가, 어느 코드에서, 쓰레드에 상관 없이 언제나 같은(동등성이 아니라 동일성) 인스턴스를 반환하도록 만들어야 해요.
저희는 이용자가 '완성' 시킨 애플리케이션에서도 싱글톤을 유지시키는 기능을 프레임워크에 만드는 거에요.

그러려면 미리 인스턴스를 생성해 두고 누군가가 `이런 타입(이름)의 객체(빈) 가져다 줘` 라고 요청하면 언제든지 동일한 인스턴스를 반환하도록 하면 좋지 않을까요?

2024-05-07 01:36 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/ComponentScanner.java
> +    private final String basePackage = "com.djawnstj.mvcframework";
이렇게 패키지를 고정해버린다면 프레임워크를 사용하는 이용자가 만든 클래스는 조회해오지 못할거 같아요.

2024-05-07 01:36 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +    }
`getBean()` 메서드에서 매번 인스턴스를 생성해주는데 이러면 싱글톤 패턴이 적용된것일까요??

싱글톤은 런타임에서 유일한 객체를 생성/사용 하는 방법이에요.

2024-05-07 01:36 UTC, djawnstj commented on src/test/java/com/djawnstj/mvcframework/bean/DynamicBeanTest.java
> +    }
검증 코드가 빠졌어요😂

2024-05-10 00:30 UTC, djawnstj requested changes
호성님 리뷰 남겼습니다!
수정해야 할 부분 남겼으니 작업해주세요~

생성한 빈들을 모아 가지고 있으면 좋지 않을까요?
그러면 `getBean` 메서드가 호출될 때마다 빈을 생성하지 않고 생성되어 있는 빈 중  알맞은 빈을 찾아 반환해줄 수 있을거 같아요.

2024-05-10 00:30 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +        return classInstance;
이렇게 하면 여러개 빈을 생성할 경우 어떻게 할까요??
예를 들어 `UserService.class`, `UserRepository.class` 모두 생성해야 하는 경우가 있을거 같아요.

2024-05-10 00:30 UTC, djawnstj commented on src/test/java/com/djawnstj/mvcframework/bean/DynamicBeanTest.java
> +                assertThat(bean).isEqualTo(bean2);
검증부가 반복문 내에 있어요😂

2024-05-10 00:30 UTC, djawnstj commented on src/test/java/com/djawnstj/mvcframework/bean/DynamicBeanTest.java
> +        Set<Class<?>> scanSet = componentScanner.scan(basePackage, Repository.class);
`Component` 애너테이션으로 찾는게 좋을거 같아요!

2024-05-11 14:58 UTC, djawnstj requested changes
호성님!
2단계도 거의 다 온거 같습니다.
몇가지 아쉬운 부분 피드백 남겨드렸어요.

추가로 테스트 클래스 중 `DynamicBeanTest` 클래스의 이름은 적절하지 않은거 같아요.
테스트 코드는 보통 클래스 명 뒤에 Test를 붙이는 방법으로 어떤 클래스를 단위 테스트 하는 역할인지 나타내고 있어요.
통합테스트라면 테스트 진입점이 되는 클래스 뒤에 IntegrationTest 등으로 구분해줄 수 있고요.

지난번에도 남겼던 피드백으로 프레임워크의 역할에 대해서 고민해봤으면 좋겠어요.
호성님이 이 프레임워크를 사용한다는 입장으로 생각해보면 어떨까요?
안드로이드를 예시로 들면 이용자가 따로 작업해주지 않아도 액티비티의 `onCreate()`, `onStart()` 등의 생명주기 메서드는 프레임워크가 호출해주고 있어요.
이처럼 프레임워크는 애플리케이션의 생명주기를 관리해야 하는 책임이 있을 수 있어요.

다시 저희 프레임워크로 돌아와서 생각해보면 '빈을 싱글톤으로 생성하고 관리한다' 는 역할이 있는데 이런 빈을 관리하려면 생명주기가 필요하지 않을까요?
안드로이드처럼 자동으로 호출해주는 기능은 나중으로 미루더라도 동적 빈 생성 이라는 역할은 어딘가에서 맡아야 할거에요.
저라면 초기화의 의미로 `init()` 메서드를 두고 해당 메서드는 생명주기 메서드로 생각할거 같아요.
프레임워크를 완성시키는 작업을 할 때 생명주기 개념을 만들고 일단 '이 생명주기에 필요한 메서드를 호출' 할거 같아요. 물론 이번 단계에서 생명주기 개념을 넣어도 좋고요.
안드로이드에서 저희가 `onCreate()` 에 적절한 메서드를 호출하는것과 비슷하죠?

`init()` 메서드에서 필요한건 `BeanFactory` 의 가장 중요한 역할인 동적 빈 생성 역할이 될거 같아요.

피드백 바탕으로 다시 고민해보고 작업하면 금방 마무리 될거 같습니다!

2024-05-11 14:58 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/ComponentScanner.java
> +        return !clazz.isAnnotation();
메서드 명은 `filteringInterface` 인데 메서드가 맡은 역할은 애너테이션이 아닌지를 확인하고 있어요
메서드/변수/클래스 명은 맡은 역할과 책임을 명확히 나타내는게 좋다고 생각합니다.

또 애너테이션이 아닌 인터페이스 타입은 필터링 해주지 않아도 될까? 에 대한 의문도 남을거 같아요.

소소한 피드백으로는 메서드 명은 동사로 시작하는것이 좋은 코드인거 같습니다~

2024-05-11 14:58 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +    private final Map<String, Object> bean = new HashMap<>();
여러 원소를 가지는 컬렉션인데 변수 명이 `bean` 인게 좀 이질적인거 같습니다.

2024-05-11 14:58 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +                throw new RuntimeException(e);
여전히 메서드의 역할이 좀 적절하지 않은거 같아요.
이용자가 `getBean` 이라는 메서드를 보고 호출하면 가지고 있는 빈들 중 적절한 빈을 찾아서 반환해줄것을 기대할거 같은데,
이 메서드가 실제로 하는 역할은 인자로 받은 타입들을 인스턴스화 하고 '여러' 빈들을 반환해주고 있어요.

2024-05-12 14:14 UTC, djawnstj approved these changes
호성님
2단계 진행하느라 고생하셨습니다~

아직 미흡한 부분이 존재하고, 몇가지 수정해야 하는 부분이 있어요.
피드백 남긴 부분 확인하시면 되고, 추가로 `BeanFactory` 의 `init` 메서드가 public 으로 구현되었는데 테스트는 존재하지 않아요.
모든 public 메서드는 필수로 테스트가 존재해야 한다고 생각하시면 됩니다.

그리고 지금까진 테스트를 작성하신게 하나의 메서드에 하나의 테스트만 존재했는데, 테스트는 메서드 하나에 여러개가 존재해야 해요.
항상 메서드가 성공하는 해피케이스가 없기 때문인데요, 실패하는 예외케이스를 만들어서 테스트만으로도 코드를 작성/수정할 때 심리적 안정감을 줄 수 있도록 만들어야 합니다.

관련된 내용은 추후에 제가 자세히 설명해 드릴테니 지금 단계에선 고민만 해보는거도 좋을거 같아요.

그럼 다음단계 진행해주시면 될거 같습니다!

2024-05-12 14:14 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +    public void init(Class<? extends Annotation> clazz) {
저는 메서드 명이 `BeanFactory` 클래스의 `init` 인데 애너테이션 타입을 인수로 받아야 하는 부분이 조금 어색하네요.
어떻게 생각하시나요?

2024-05-12 14:14 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/BeanFactory.java
> +    }
생성자 사용 굳!! 👍🏻

2024-05-12 14:14 UTC, djawnstj commented on src/main/java/com/djawnstj/mvcframework/bean/ComponentScanner.java
> +                .filter(clazz -> !clazz.isInterface())
`filter` 메서드를 두번 사용해서 `!clazz.isAnnotation()`, `!clazz.isInterface()` 이렇게 두번 조건문을 넣엇어요.
이러면 스트림 순회를 두번하게 돼서 성능적 손해가 생길것 같아요.
기본 애플리케이션도 물론 성능을 크게 고려해야 하지만 프레임워크/라이브러리 라면 불필요한 성능 저하는 줄여야 하지 않을까요?

저라면
``` suggestion
                .stream()
                .filter(clazz -> !clazz.isAnnotation() && !clazz.isInterface())
```
이렇게 할거 같네요.

2024-05-12 14:14 UTC, djawnstj commented on src/test/java/com/djawnstj/mvcframework/bean/BeanFactoryTest.java
> +    }
메서드 설명과 이름은 `"조회한 클래스 정보들을 이용해 빈 생성"`, `createBean` 인데 검증하는 메서드는 `getBean` 이네요😂
이러면 메서드를 보고 추측한 테스트가 실제 검증과는 달라서 매번 테스트 내용을 확인해야 하는 문제가 있을거 같아요.

테스트는 이 테스트로 어떤걸 검증하고 싶은지 확실히 알려줘야 해요.

2024-05-12 14:14 UTC, merged